### ISSUE TITLE
Entry point?

### ISSUE THREAD

**Issue by MichaelCurrie** [nickswalker/paper-marbling-js#1]
Hi there,

I am looking for a marbling simulation but I cannot see how to try yours here.  Is it implemented?  Thanks

**Comment by nickswalker** [comment]
Yes, it's available at https://marblizer.nickwalker.us
I've put this link in the Readme to make things more clear. Let me know what you think!

**Comment by MichaelCurrie** [comment]
Cool!

![download](https://cloud.githubusercontent.com/assets/5267078/22264553/a002d712-e235-11e6-857d-42b0de97dfe9.png)

It would be nice to be able to add a grid of colours like what is seen in this video which first introduced me to marbling:

https://www.youtube.com/watch?v=Vyga8VMWXKg
